# Generated by Django 6.0 on 2025-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
